jenkins:
  securityRealm:
    ldap:
      configurations:
        - managerDN: ${ldap_ManagerDN}
          managerPasswordSecret: ${ldap_ManagerPasswordSecret}
          rootDN: ${ldap_RootDN}
          server: ${ldap_Server}
          userSearch: ${ldap_UserSearch}
  # Best-Practice: RBAC as authorization
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
