jenkins:
  securityRealm:
    ldap:
      configurations:
        - managerDN: ${ldapManagerDN}
          managerPasswordSecret: ${ldapManagerPasswordSecret}
          rootDN: ${ldapRootDN}
          server: ${ldapServer}
          userSearch: ${ldapUserSearch}
  # Best-Practice: RBAC as authorization
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
