jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: ${jenkinsPass}
        - id: "developer"
          password: ${jenkinsPass}
        - id: "guest"
          password: ${jenkinsPass}
  # Best-Practice: RBAC as authorization
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
